### ISSUE TITLE
Fashion recommendation system by Bibin Karthikeyan Krishna

### ISSUE THREAD

**Issue by rjeantet** [TechLabs-Berlin/project_proposals#10]
### What is your project's name?
Fashion recommendation system
### What problem are you trying to solve?
To enhance user engagement by providing features like personalized styling, trend integration, and a visually appealing interface.
### What is your idea for a solution to the given "problem"?

- Develop a simple user profile system where users can input their style preferences, favorite brands, and preferred clothing types.
- Integrate a list of currently trending clothing items or styles.
- Implement a basic trend analysis by tracking the popularity of items within the system.
- Basic predictive modeling to anticipate future trends, by analyzing historical data and identifying patterns in the emergence of new trends

### Which tracks do you think could be involved?
UX, WD, DL/DS
### *How do you imagine Deep Learning and/or Data Science could contribute to this project?*
- Researching and exploring the available data
- Developing straightforward recommendation algorithms, 
- Analyzing image attributes of clothing like color, pattern, etc. 
- Identifying trends by analyzing the frequency of certain styles or brands. 
- Analyze historical data and identify trends and pattern recognition to predict future trends.

### *How do you imagine User Experience Design could contribute to this project?*
Designs a clean, intuitive, visually appealing user-friendly user interface for the recommendation system.
### *How do you imagine Web Development could contribute to this project?*
Implements the backend and frontend components of the recommendation system, working closely with the UX designer.
### What are the most important challenges & bottlenecks of your project?
Availability of data
Limited technical expertise: lack of experience
Effective team collaboration: communication gaps and challenges in aligning the contributions of beginners with different roles.
### What are the most important success factors of your project?
Being aware of the challenges embracing a collaborative approach, seeking guidance, and using the project as a valuable learning experience.
### Share your resources here:
https://www.kaggle.com/code/marlesson/building-a-recommendation-system-using-cnn-v2
https://libguides.library.kent.edu/c.php?g=278163&p=1853989
https://www.stitchfix.com/
https://www.kaggle.com/code/bhanupratapbiswas/hybrid-recommendation-system-using-python
### Do you have any other remarks?
The links added are just references that don't exactly align with the attributes of the project!

**Comment by rjeantet** [comment]
Hi Bibin!
Thanks for submitting your project idea!
It is pretty thorough by now! The idea is well defined, the scope as well, and you have started your research on the datasets needed, so I do not have much requirements to add to it.

The suggested team requirements would be:

- [ ] 1 UX Techie
- [ ] 1 UX Techie
- [ ]  1 WD Frontend Techie
- [ ]  1 WD Backend Techie
- [x]  1 DS Techie (that's you Bibin @Lidiyan)
- [ ]  1 DS Techie
- [ ]  1 DL Techie

Your project will remain on the scoping stage for another couple of days to give a chance to other Track leads to provide additional comments if needed. Afterwards, I would move it to approved and open for team composition.

**Comment by Lidiyan** [comment]
Hi Rose
Thank you so much . That's positive, but if you do come across any useful datasets or any other recommendations please do share them. Much appreciated.

**Comment by valiantone** [comment]
Hey @Lidiyan here's an example of a dataset: https://github.com/zalandoresearch/fashion-mnist

A comment from my side would be that once you have more DS/DL colleagues, do have a conversation about who will develop the image recognition parts (DL) and the fashion recommender based on tags (DS) as they are two very separate ways to deliver this app and will decide the direction even for team assignment.

**Comment by rjeantet** [comment]
Awesome! Thanks @valiantone for jumping in!

@Lidiyan: your project is clearly defined so I am moving now your project to accepted so you can start recruiting team members 💯 Of course do not hesitate to enrich if you have further specific questions or if you want to share additional findings with your future teammates 👍🏼

**Comment by sfngrz** [comment]
Hi @Lidiyan,

Stefano here from the WD track, still looking for FE?

**Comment by Lidiyan** [comment]
Hi Stefano
Yes, of course. I wasn't sure how to convince someone to be a part of the project. I just thought if someone might be interested, then they would join themselves. Thank you. We will be a team then.

**Comment by sfngrz** [comment]
Hey @Lidiyan sorry for the late reaction. I didnt know who had open spots, so I asked my 3 favourite projects and well you all replied positively, but since I couldnt get to decide myself which one of the 3, a little bird involuntarily did it for me. So I unassigned myself from here. Hope youll get enough to start with it!
