### ISSUE TITLE
happy sport happy life by Weronika Ajimati

### ISSUE THREAD

**Issue by valiantone** [TechLabs-Berlin/project_proposals#11]
### What is your project's name?
happy sport happy life

### What's the problem you are trying to solve?
Community Building: Creating an online platform where IT professionals can connect and share their daily routines and activities.Healthy Habit Promotion: Integrating features that allow users to suggest and discuss health-focused habits and routines.Engagement and Interaction: Designing interactive elements that foster user participation, such as forums, habit tracking, or routine-sharing capabilities.My goal is to design and develop a supportive community environment focused on balancing professional demands with physical well-being and active habits.

### What's your idea for a solution to the given "problem"?
Stand-Up Alert: Every 15 minutes, a prompt to stand and perform a brief activity, such as fetching water from the kitchen or checking the postbox.Screen Break Notification: Periodic reminders to take a break from the screen and observe the outdoor weather.Activity Suggestion: Following these prompts, if an inclination for a specific activity is felt, a reminder for that particular activity will be issued. If no such hobby exists, a gentle reminder to take a short walk or arrange a meeting with friends at least twice a week will be provided.

### Which tracks do you think could be involved?
UX

### How do you imagine User Experience Design could contribute to this project?
Ease of Use: UX Design focuses on making the website easy and intuitive to navigate. This means users can find what they need without confusion, whether it's sharing routines, accessing health tips, or engaging in community discussions.Engagement: Good UX keeps users interested. For my site, this could mean designing interactive features like habit trackers or forums in a way that's fun and inviting.Community Building: UX can help design spaces for users to interact, share experiences, and offer support, fostering a sense of community.Accessibility: It's important that my website is usable by everyone, including those with disabilities. UX Design ensures that text is readable, navigation is straightforward, and the site is usable on different devices.Feedback Integration: UX Design involves listening to user feedback and making adjustments to improve the site continuously.Aesthetics: A well-designed site that looks good and feels cohesive can make users more likely to return and engage with the content.In essence, UX Design is crucial for making sure my website is not just functional, but also a pleasant and engaging place for my target audience. Even without prior experience in UX, understanding its importance is a great first step in developing a successful website.

### What are the most important challenges & bottlenecks of your project?
Keeping Users Active: Ensuring users regularly visit and use the site.Building Community: Creating a welcoming and interactive community space.Quality Content: Providing accurate and useful health and lifestyle tips.Handling Growth: Making sure the website can support more users over time.Protecting User Data: Ensuring user information is secure and private.Making it Accessible: Designing the site to be easy for everyone to use.Funding: If needed, finding ways to financially support the site.Attracting Users: Effectively marketing the site to reach the right audience.

### What are the most important success factors of your project?
Strong Community Engagement: Active participation and sharing by users.High-Quality Content: Relevant, useful health and lifestyle information.User-Friendly Design: Easy navigation and accessibility for all users.Effective Marketing: Reaching and attracting the target audience.Consistent User Growth: Steadily increasing the user base.Positive User Feedback: Users finding value and benefit from the site.Data Security: Protecting user privacy and information.Sustainable Operations: Maintaining financial and operational stability.

### Share your resources here:
Public Health Data: Websites like [WHO](https://www.who.int/)  or [CDC](https://www.cdc.gov/) offer datasets related to health and wellness. Fitness Activity Data: Platforms like [Kaggle](https://www.kaggle.com/) often have datasets related to physical activities and fitness. Platforms like [YouTube](https://www.youtube.com/) or [Coursera](https://www.coursera.org/) for tutorials on website design, UX, and community building. Online Articles and Blogs: Look for articles on health-focused websites that discuss engaging IT professionals in wellness activities.Blogs about community building and user engagement, especially in health and wellness spaces.

**Comment by catarinalouza** [comment]
Hi Weronika, nice idea, thanks for submitting! 

Some important questions came up about your idea. We are wondering why you only mention the UX track should be involved? TechLabs projects usually involve more than one track. Were you unsure how the other tracks can be involved or your initial thoughts were to have a UX-only team? Before giving you more specific feedback on the idea and your plans for it to help you define the scope, it would be great if you could clarify how you see your team formation!

I think your idea can definitely be doable together with Web Development techies, to build the product you'll be working on during your research. It would benefit from scaling down the scope, specially considering the amount of time you will all have to work on it.. For DS/DL, let me call @valiantone to help us see if they are needed for your idea!

**Comment by valiantone** [comment]
My first instinct is you will need at least some WD techies to assist with this and maybe even some DS techies. Let's try and complete this idea a little bit! Some improvements:
- Let's add some WD techies. With even the features you listed (sharing routines, profiles, recommendations) you will need both FE and BE developers to build it out!
- Even if you started with writing only a few recommendations just for MVP, your delivery would be much more impressive if you used some DS techies to find a dataset with health recommendations and make for ex suggestions based on people's lifestyle (which could be a part of their profile). The DS techies should be able to devise some suggestions based on analysis of profile and some computation/algorithm on their side.

**Let us know if you agree or have any other suggestions from your side to include more tracks and clear acceptance criteria for this proposal ✅**

**Comment by werka93** [comment]
Hi both, thanks for your comments and suggestions. I guess I missed out the team structure part. I of course i expect to include the WD, and DS to successfully execute the project.

**Comment by werka93** [comment]
Team formation

WD
DS
UX

**Comment by valiantone** [comment]
Agreed, moving this to `Accepted`. You may now go ahead and recruit your team.

### Team Formation Requirements
- [ ] 1 WD (FE)
- [ ] 2 DS
- [ ] 2 UX
- [ ] 1 WD (BE)
