### ISSUE TITLE
Investment guide by Elena Iurchenko-Matlas

### ISSUE THREAD

**Issue by mistersouza** [TechLabs-Berlin/project_proposals#16]
This project is incredibly promissing, and I'm very enthusiastic about participating in it. I am currently at the ux track, looking forwarding to helping you building up your idea.

**Comment by valiantone** [comment]
Hey @mistersouza I added your comment to the correct issue #8. Please do not create any new issues, but make your comments on existing issues to keep the conversation in one thread! Thanks 🙏🏽 

Closing this issue as duplicate.
