### ISSUE TITLE
charge finder by Mana Nosrati

### ISSUE THREAD

**Issue by valiantone** [TechLabs-Berlin/project_proposals#17]
### What's the problem you are trying to solve?
There are some times that your mobile phone is running out of charge and you need to recharge it as soon as possible and you are in the bus/train station, but you do not know where and how you can charge your mobile phone. Finding the area to charge my phone.

### What's your idea for a solution to the given "problem"?
creating an app to show the nearest bus/ train stations where you can charge your cellphone. however, at first, it is needed to create these areas in stations, that use solar energy or kinetic energy.

### Which tracks do you think could be involved?
UX

### How do you imagine Deep Learning and/or Data Science could contribute to this project?
No response

### How do you imagine User Experience Design could contribute to this project?
by creating an app to show people how and where they can have access to charging areas.

### What are the most important challenges & bottlenecks of your project?
create charging areas in bus and train stations

### What are the most important success factors of your project?
to be as simple as possible

### Would you like to add an optional Pitch deck to support your idea in 6 to 8 slides?
[Slides](https://docs.google.com/presentation/d/1Kd-79TdJWwb_BGwi2USiKR79NBhZ5YelXozL2XEl7nI/edit?usp=sharing)

**Comment by catarinalouza** [comment]
Hi Mana, nice idea, thanks for submitting! Some important questions came up about it. 

> Which tracks do you think could be involved?
> UX

We are wondering why you only mention the UX track should be involved? TechLabs projects usually involve more than one track. Were you unsure how the other tracks can be involved or your initial thoughts were to have a UX-only team? Before giving you more specific feedback on the idea and your plans for it to help you define the scope, it would be great if you could clarify how you see your team formation!

I think your idea can definitely be doable together with WD techies, to build the website or web-app you'll build with the charger's locations. You'll need some DS techies too to gather data on the stations that have charging locations.

**Comment by Mananosrati** [comment]
Hi Catarina, sorry for responding with delays. 
I wasn't so sure how to involve other tracks. Yes, I need all of them UX, WD and DS.
 Thank you for your help.

**Comment by valiantone** [comment]
Hey @Mananosrati, wanted to point out a few things. This proposal is definitely lacking details on how other tracks will contribute, details on tasks, how you plan to tackle some bottlenecks and challenges etc.

Since there has been no discussion, or other techies showing any interest in this, also we have moved past our deadline of scoping a project and getting it accepted, **I would recommend not moving this project proposal ahead and looking for an alternative project to join. Let me know if you agree?**

Probably, not what you want to hear but just trying to be realistic given current timeline and feasibility of project. Thoughts?

**Comment by Mananosrati** [comment]
Hello,
Yes, I understand. Then I will try to look for an alternative project. Thank you for your help.
