### ISSUE TITLE
ClimeFleet Analytics by Muhammad Shahrukh

### ISSUE THREAD

**Issue by catarinalouza** [TechLabs-Berlin/project_proposals#19]
### What is your project's name?
ClimeFleet Analytics

### What's the problem you are trying to solve?
Transportation is an integral part of any business to function, whether it is about procuring raw materials from another state/country or delivering the end products to the customers. No matter what type of transportation medium is taken, it has a cost associated with it and so are the carbon dioxide emissions released as a result of the activity.

### What's your idea for a solution to the given "problem"?
With increased regulations from governments and consumers, questions are often raised by such audiences/ entities towards the enterprises to report their carbon footprint that is associated with the product in order to make informed decisions when buying such products. Here ClimeFleet Analytics comes into play by helping businesses solve this complex problem of emission hotspots in their supply chain.

### Which tracks do you think could be involved?
DL/DS, WD, UX

### How do you imagine Deep Learning and/or Data Science could contribute to this project?
As I am doing the DS track, therefore I imagine myself doing the data analysis for carrying out the calculations of transportation emissions associated with the different activities that the business might have (Upstream or Downstream carbon calculations).
This would mainly include researching about the correct emission factors (EFs) to implement that are as accurate as possible.
Later this database of EFs will be used to map out on to relevant activity of transportation such as the amount of distance traveled by a vehicle, and the mode of transport that has been used (Freight, Long Haul ships, Road Transport, etc.)

### How do you imagine User Experience Design could contribute to this project?
A UX techie will be needed to make the analytics of such transportation emissions or transportation data, in general, more visually appealing so that the infographics will help businesses make informed decisions about the relationships between various contributing factors towards high cost/ emissions in the supply chain.
The techie will be part of the team that designs the user interface of the app such as the dashboard where the user will always have their data readily available. A separate interface will be needed where the user will enter their relevant business operations data such as (fuel type used, amount of fuel used, type of vehicle, mode of transport, etc.)

### How do you imagine Web Development could contribute to this project?
A backend Developer will be required for this project who will store such large amounts of data in a database and connect the app from backed point of view to retrieve all the raw data that is entered into the system by the user.
A frontend developer will be required to connect all the different wireframes that will be produced by the UX techie into sequential landing pages for the users to navigate across different inputs forms (depending on the data that user inputs)

### What are the most important challenges & bottlenecks of your project?
From a project perspective, the main challenges would encompass all the Scope 3 transportation emissions, as these emissions can include more intricacies such as finding out the EFs of a specific transportation vehicle (where even researchers tend to get confused going down the rabbit hole for example model of the vehicle, horsepower or fuel efficiency) hence we may use industrial average data for doing these analyses.

Another challenge/ bottleneck would be the user entering the wrong corresponding units of the actual data, an example of this would be their distance traveled is measured in miles, but instead the user enters it in kilometers, therefore the corresponding multiplication factor is to be considered when perform data analysis of this kind of data.

### What are the most important success factors of your project?
A seamless user experience will enhance the usage of the app when all the important metrics are visible to the user, they are able find out relations between such metrics.

A forecasting feature would even help the users to estimate the emissions that can be emitted during the course of the year they are allowed as an entity.

Reports generation will be a crucial aspect of the app, where the user can have an overview of all the business operations that are taking place and perform their own analysis on conducting their business in order to either reduce their emissions or maximize their profits.

### Share your resources here:
[GHG Protocol for following the emissions calculation methodology](https://ghgprotocol.org/scope-3-calculation-guidance-2)

**Comment by valiantone** [comment]
Okay, good amount of details in the pitch @shahrukhzaidi. A few standard checklist questions that need to be answered:

### UX
This is a specialized software application for expert users. To help with design would you be able to provide UX techies with access to 2-3 users who would be target users to test and use the product?

### DS/DL
All sounds good, looks like you have a starting point. **Do not see any way DL techies can be added to your project but we'll see if anyone is interested and has an idea on how they can contribute.**

### WD
All good, you have a strong starting point.

If you can respond to the UX question. We can move the project to `Accepted` and prepare for team formation.

**Comment by shahrukhzaidi** [comment]
Hi @valiantone,

Thank you for your feedback. As I am already a professional in the field of sustainability, I have a LinkedIN community of such professionals who can definitely spare some time out to user-test the app and provide valuable feedback around it. 

Also do you think 1 UX techie would be sufficient for this kind of a project?

**Comment by valiantone** [comment]
Thank you that takes care of our concerns, we can now move this forward! We would recommend the following team formation, let us know if you agree!

### Team Formation Requirements
- [ ] 2 DS
- [ ] 2 UX
- [ ] 1BE (WD)
- [ ] 1FE (WD)

**Comment by sfngrz** [comment]
Hi @shahrukhzaidi!

Stefano here from the WD track! Nice idea here, do you still need any front end dev for the project?

**Comment by shahrukhzaidi** [comment]
Hi @sfngrz ,

Thank you for your interest in the project, yes there is still a spot for a FE developer available and looking forward to how we can go onwards from here. 🚀 
In the coming days, I will be creating a MIRO board where we can collaborate on our workflow. Also, I am flexible enough to hear about your ideas as well on how you would want to contribute towards the project. 😃

**Comment by sfngrz** [comment]
> Hi @sfngrz ,
> 
> Thank you for your interest in the project, yes there is still a spot for a FE developer available and looking forward to how we can go onwards from here. 🚀 In the coming days, I will be creating a MIRO board where we can collaborate on our workflow. Also, I am flexible enough to hear about your ideas as well on how you would want to contribute towards the project. 😃

Cool, cant wait to see who's in then we can start to discuss!

**Comment by shahrukhzaidi** [comment]
> > Hi @sfngrz ,
> > Thank you for your interest in the project, yes there is still a spot for a FE developer available and looking forward to how we can go onwards from here. 🚀 In the coming days, I will be creating a MIRO board where we can collaborate on our workflow. Also, I am flexible enough to hear about your ideas as well on how you would want to contribute towards the project. 😃
> 
> Cool, cant wait to see who's in then we can start to discuss!

As per the requirements from @valiantone, the team should consist of 

2 DS (Shahrukh/....)
2 UX
1BE (WD)
1FE (WD) (Stefano)

I have created a (https://miro.com/app/board/uXjVN0zl23Y=/) Miro board already and will be populating things around the project by tonight.
Let's have a meeting soon once we have a team formed.

**Comment by Mananosrati** [comment]
Hi there,
That is a nice idea, I would like to join your team as a UX member.

**Comment by shahrukhzaidi** [comment]
Hey @Mananosrati,

Glad that the project resonates with you and I would be happy to have you on board as a UX techie then. 😄 

2 DS (Shahrukh/....)
2 UX (Mana Nosrati/.....)
1BE (WD)
1FE (WD) (Stefano)
