### ISSUE TITLE
Community-powered concert tracker/recommender by Can Yilmaz

### ISSUE THREAD

**Issue by catarinalouza** [TechLabs-Berlin/project_proposals#20]
### What is your project's name?
Community-powered concert tracker/recommender

### What's the problem you are trying to solve?
Berlin is a big city, full of events, especially musical ones. Although there are apps/platforms that list concerts by "well-known" artists, it's very difficult to find events by lesser-known artists, amateurs...

The problem is all the more difficult when your musical tastes are particular and correspond to a music scene that doesn't have a wide audience. Generally speaking, to access this kind of information, you already need to be connected to a community organized around a specific genre.

The problem obviously works the other way round. Less-known artists find it difficult to connect with a wider audience or even with their potential audience.

Many of these events take place in bars, restaurants, associations, schools or as part of one-off events. They can be concert, mini-concert, jam-session, open-mic etc., mostly free events or events which do not have ticket sales but a small on-site entrance fee. This is, by the way, one of the reasons why these events are not listed, or are poorly listed, by existing platforms.

In the end, information is difficult to access, it requires too much effort. Although motivated, we find ourselves missing out on a lot of concerts.

### What's your idea for a solution to the given "problem"?
A platform which lists all the concerts and musical events which are not, or are poorly listed by existing platforms.
A platform with the goal of connecting the right concert, at the right time, at the right place to the right person.
A platform with two main features:

1. Community-powered
Of course we will list events ourselves but so will  musicians and organizers with an account. They will be able to submit their events directly to the platform. Since informations are hard to find for less-known artists, it seems to be a judicious choice to successfully capture small events.
2. Using data science
By using machine learning methods, we hope to offer a more precise classification of events, a more intuitive search system as well as a more relevant recommendation system. All this, allowing us to connect the public to all its potential artists, and the artists to all its potential audiences.

### Which tracks do you think could be involved?
DL/DS, WD, UX

### How do you imagine Deep Learning and/or Data Science could contribute to this project?
We have huge Spotify datasets available in which we have access to different characteristics to define an artist or a song. These can be criteria such as genre or subgenre, release date, country etc. but even more interesting are certain attributes such as: acousticness, danceability, duration_ms, energy, instrumentalness, key, liveness, loudness, mode, speechiness, tempo, time_signature, valence.

By applying ML models on these datasets, it is theoritically possible to find classification criteria allowing us to develop a relevant classification/search/recommendation system on our platform to connect an artist/event to an audience/user.
The use of ML represents one of the two main components of the project.

Being in the DS track myself, I have so far only been able to think within the framework of this type of skills. But obviously, there would surely be more features to develop involving DL. The project is completely open to proposals in this direction.

### How do you imagine User Experience Design could contribute to this project?
The project proposed here aims to be able to be used by as many people as possible, we will  need UX designers in the project in order to make the platform use simple and instinctive.

### How do you imagine Web Development could contribute to this project?
By creating the plateform :)
The project would be more relevant in mobile app format. I don't know if that would be possible.

### What are the most important challenges & bottlenecks of your project?
Quickly agree as a team on the main outlines of the MVP
Be able to deploy the proposed machine learning solution.
If possible develop the project as a mobile app.
To have a simple and fun user interface

### What are the most important success factors of your project?
For the success of the platform: organic communication, offer the platform to all musician communities in Berlin. A free communication tool for events can only be welcomed if it is easy to use. The musicians' entourage and the musicians themselves will be enough to form the community of active early adopters.

### Share your resources here:
https://www.kaggle.com/datasets/jfreyberg/spotify-chart-data
https://www.kaggle.com/datasets/rodolfofigueroa/spotify-12m-songs
https://www.kaggle.com/datasets/nikitricky/every-noise-at-once
https://everynoise.com/
https://spotipy.readthedocs.io/en/2.19.0/#

**Comment by valiantone** [comment]
Good proposal, well documented @cnymz. I think the only open questions would be on DS/DL side. You seem to be creating a lot of the metrics using community, but a huge factor in project success is in being able to acquire event/concert data very fast. Without this applying DS will be difficult and even BE would end up waiting a long time for their data. 
- **Have you confirmed the existence of concert datasets in addition to the music categorical datasets?** 
- **Do you plan to only use spotify datasets or even live info using spotify API?** Both are acceptable options.

On UX and WD sides, task is straight-forward and we do not see any hurdles. If you just respond to the DS concerns, we can start discussing team formation and move the project to `Accepted`.

**Comment by cnymz** [comment]
Hi @valiantone, thanks a lot for the feedback!

1. Unfortunately, I haven't found any ready-to-use concert datasets yet, I don't know if there are any for that matter. Although I hope the platform will one day be sufficiently populated by the community, for the purposes of the project, I think it's possible to enter enough gig data manually in the first instance. Eventually, we'll surely be able to extract this information from other platforms offering public API. We could consider doing this now, but it's something we'll have to discuss as a team, especially with the advice of the BE dev and the mentors.


2. At first I had in mind to use Spotify APIs. The problem is that I'm not sure how difficult the operation is. What's more, I've read that Spotify's API rate-limit isn't very generous. So I didn't want to depend on this parameter for the feasibility of the project. It's still possible, but to be discussed with the team and mentors.
There are other datasets available, such as those from Last.fm and Million Song datasets. They are also very well supplied and relevant to the project. Each has features that would allow a different approach to the problem, and even they could theoretically be combined... For the moment, I've only presented the Spotify datasets, as they were sufficient to justify the feasibility of the project.

**Comment by valiantone** [comment]
So, a lot of this sounds like you are rerady to go and final decisions can be made after team formation, so let's proceed with that!

### Team Formation Requirements
- [ ] 1-2 DL
- [ ] 2 DS
- [ ] 2 UX
- [ ] 1BE (WD)
- [ ] 1FE (WD)

**Comment by cnymz** [comment]
Hi @valiantone.
Sorry I'm a bit late in replying :) Thanks for the validation !
Just one question : in the team composition, when you say 2 DS, does that include me?
