### ISSUE TITLE
domfix by Farida Elchuzade

### ISSUE THREAD

**Issue by valiantone** [TechLabs-Berlin/project_proposals#23]
### What's the problem you are trying to solve?
The problem that I am trying to solve is the difficulty of finding and hiring reliable local service providers. This can be a time-consuming and challenging process, especially for people who are unfamiliar with the area.

### What's your idea for a solution to the given "problem"?
To create a user-friendly platform that connects residents with local service providers in a variety of categories, including plumbing, electrical, cleaning, renovation, etc. The platform will provide detailed provider profiles, ratings, and reviews, photos of their work empowering residents to make informed decisions about their service needs.

### Which tracks do you think could be involved?
- WD
- UX
- DL/DS

### How do you imagine Deep Learning and/or Data Science could contribute to this project?
Analyzing the users' problems and matching them with the best match service providers.

### How do you imagine User Experience Design could contribute to this project?
User Research: Conduct thorough user research to understand the needs, behaviors, and pain points of both service providers and residents. This includes identifying what residents look for in a service provider and the challenges providers face in marketing their services.

Creating detailed personas and user journey maps to visualize the typical paths users take when interacting with the platform, from discovering services to booking and providing feedback.

Information architecture to make it easy for developers to understand the process.

Create low and high-fidelity wireframes (annotations for developers).

Create a working prototype.

Design a clear Booking Process.

### How do you imagine Web Development could contribute to this project?
Front-End Development:
- Build a responsive website (web app) where users can search for services and book them.
- Build an admin dashboard for service providers to track the record of services they have been providing.

Tech stack: HTML, CSS, JavaScript, React.

Back-End Development:
- Build an API that supports the website such as authentication, booking, search

### What are the most important challenges & bottlenecks of your project?
Getting User Data to Personalize Experiences.
Gathering and organizing data.
Data privacy and security.
Limited technical expertise.

### What are the most important success factors of your project?
A working platform with a list of providers and reviews.
User-friendly and engaging platform.
Easy booking process.
Easy search for services.

### Share your resources here:
These are similar platforms where you can search for repair services:
https://www.my-hammer.de/
https://support.taskrabbit.com/hc/en-us
https://armut.com/en-yakin/istanbul-34 (Turkish)

### Would you like to add an optional Pitch deck to support your idea in 6 to 8 slides?
- [Slides](https://drive.google.com/file/d/1eICi_zFAzdA9XZ0ujEyWXM1iRwyJgsQ0/view?usp=sharing)

**Comment by valiantone** [comment]
All right, thanks for the details @faridaelchuzade, since you're a veteran I thought we'd just get down to some core details.

### UX
We good on tasks for UX, seems plenty. Again, since you are advanced, have you thought maybe narrowing/defining the scope of your users to residents (test in one single building), service providers or general audience could aid in providing a more targeted goal to all interested techies. **You can make a choice with team later but if you already have preferences feel free to share. Since it's a week 3 kind of decision, like to prod early.**

### WD
Very well defined, we are set. Real tasks to be delegated by team.

### DS
Just a suggestion here, but  more concrete tasks for DS techies could be identifying needs from post and suggesting recommendations, ranking as per parameters (though that can also be done by WD), build a matchmaking service/algo etc. Always good to have a few prompts to help move team ideation along.

Let us know your thoughts and we can move this to `Accepted` and finalize team formation requirements.

**Comment by faridaelchuzade** [comment]
Hi Zubin,

That sounds good to me, we can add the mentioned tasks to DS.

**Comment by valiantone** [comment]
Awesome, then consider this project ffinal for team formation. Moving to accepted! go ahead and start recruiting a team.

### Team Formation Requirements
- [ ] 2 DS
- [ ] 2 UX
- [ ] 1BE (WD)
- [ ] 1FE (WD)

**Comment by mahanfa** [comment]
Hello Farida, nice idea and presentation. I would like to be a part of your team as a UX designer. Bests.

**Comment by Mananosrati** [comment]
Hi Farida, 
it's a nice idea.  and I would like to be a part of your group as a UX designer.

**Comment by mahanfa** [comment]
Hello Farida,
This is a nice idea and presentation and I would like to be a part of the team as a UX designer, if that is possible. Bests

**Comment by faridaelchuzade** [comment]
Hi @mahanfa can you please message me on slack so I can tag you to add you to the project?

**Comment by mahanfa** [comment]
> Hi @mahanfa can you please message me on slack so I can tag you to add you to the project? 

Hello, I deleted my comment because I thought it might have made you not see the comment from the previous person above me. Okay I'll do that.

**Comment by werka93** [comment]
Hi Farida, it's a really nice and good idea. I would like to join your group as a UX designer.
