### ISSUE TITLE
Feminizidmap by Paula Hierzi

### ISSUE THREAD

**Issue by rjeantet** [TechLabs-Berlin/project_proposals#4]
### What is your project's name?
Feminizidmap
### What's the problem you are trying to solve?
So I want to support this Kollektiv in Analyzing their collected Data. But I don't have a go from them jet. And I am unsure how many people they need and from which tracks.
### What is your idea for a solution to the given "problem"?
Ordering and sorting their data so it is easily callable (Panda?). Analyzing with the help of Matplotlip and making data visible. Helping them make it clear and easily accessible (UX Design) on their website(WebDev)
### Which tracks do you think could be involved?
DL/DS, WD, UX
### *How do you imagine Deep Learning and/or Data Science could contribute to this project?*
DataScience I can imagine. I am in the Data Science track and they need a Data Scientist not clear how many.
### *How do you imagine User Experience Design could contribute to this project?*
Make the Data easily readable. On the website but also on presentations ...
### *How do you imagine Web Development could contribute to this project?*
Update the website with all the information
### What are the most important challenges & bottlenecks of your project?
Not sure yet
### What are the most important success factors of your project?
Being able to use the data to make things visible
### Share your resources here:
current website of the Kollektiv: https://feminizidmap.org/

### Do you have any other remarks?
I would submit a presentation once I have a clear go of how many people they need and what their main needs are

**Comment by rjeantet** [comment]
Hi Paula @Rustingheart , happy to review and help you get going with this idea!

### First, a personal opinion: 
The goal of this project in particular is truly meaningful and vocational which in itself is already beautiful, but if/when it goes through to completion, having on their portfolio a live project being used by a non-profit is a strong advantage for all of the team members.

Now, here are a few pointers to clarify before your idea can be moved forward to scoping status:
### 1 - About the dataset: 
The feasibility of this project is extremely dependent on whether the collective would share their data or not. Since you are in DS already, we suggest you to:
- [ ] **Search for alternative dataset** to make sure the project can happen whether the collective shares their data or not.

### 2 - project ownership 
All projects must have equal ownership between all team members: ideally, decisions are made collectively and with the help of mentors, but UX is ultimately the one making design decisions, same for WD, DS, DL...etc... for technological decisions. In this specific case, this means that the collective will not be able to validate wireframes or require specific technology stacks. What they would get is a project delivered that they are free to host and use in exchange for opening their DB to you. Also reference to the Techies that worked on the project should then be added to their contribution page.

- [ ] You should **confirm with the collective that this is something they would agree on** before the project can be moved on to scoping.

### 3- WD & integration with their website 
This is a bit redundant with the previous point, but the collective is using Hugo, a static website framework whereas the Techies will be using some different stack that they build from scratch. For this reason, the project can not be integrated directly into their website. There are other solutions like hosting independently and linking it, which can be discussed with the WD team and / or mentors.

- [ ] Communicate to the collective that **Techies will not be working on their existing website/technologies**, but rather create a new project that the collective will be 100% host and use.

### 4 - team constitution
DL is not needed for the scope of this project, so our suggestion is:

- [ ] 1 to 2 UX, 2 WD (frontend & backend), 1 to 2 DS**

<br><br>

Well done and thanks again for submitting your ideas. 🥇

**Comment by Rustingheart** [comment]
Thank you so much for the Feedback! 
This is very helpfull!

**Comment by Rustingheart** [comment]
I sadly think I might have to cancel this one. Since I feel they need tooo much time to know exactly what they need. So I am afraid we can not do it in time.  Not totally kicking it out. Just so people know!
But still very interested to do a similar topic so anyone who wants to go that direction please Contact me!

**Comment by rjeantet** [comment]
Hey Paula!
Sorry to read this is not moving fast enough on their side, this is indeed the risk pointed out with projects involving third-parties. It is a shame as this project is so meaningful and would be very interesting to work on for all tracks involved.

If you or another DS Techie is keen on it, I would indeed suggest researching some similar alternative datasets and keeping going on this idea, independently from the collective decisions.

**Comment by Rustingheart** [comment]
Just as an update for everyone! 
Whoever is interested. 
I am thinking of another DataSet to Analyze right now. 
We can also chat and decide together.

**Comment by Rustingheart** [comment]
Hi hi an update from my side!
So I am proposing two new DataSets here that are connected to Protest (1.Worldwide)(2. Europe).
https://dataverse.harvard.edu/dataverse/MMdata

https://poldem.eui.eu/data-overview/

My personal resaon to choose those DataSets:
As I have been researching in my last BA (Dance). 
What Gestures can express when a large Group does the same Unisono (>MassProtests).
Which Gestures get World-Fame and why ?
T

**Comment by rjeantet** [comment]
Closing this since it is being replaced by [Mass Protest Cross Countries ](https://github.com/TechLabs-Berlin/project_proposals/issues/13)
& @Rustingheart amazing job of pivoting your idea when facing difficulties !!
