### ISSUE TITLE
Home Routine Organizer by Elena Iurchenko-Matlas

### ISSUE THREAD

**Issue by catarinalouza** [TechLabs-Berlin/project_proposals#5]
### What is your project's name?
Home_Routine_Organizer

### What's the problem you are trying to solve?
Housekeeping a kind of taks that everybody have to do, independent if you live in a sharing flat or still with your parents and if your are self mom/dad and have kids. The problem is that nobody have time for these tasks. Times are hard, women/men have fulltime jobs and have enough to do with kids after school and kindergarden, but if we share every task randomly withing a family/sharing flat group etc. this will takes just small peace of time and will help to keep houskeeping in flow. And the best thing is that nobody is going to be overloaded with all these task forced to do it alone.

### What's your idea for a solution to the given "problem"?
To create an application or its prototype in phyton that checks the data (time slots and data filled in it) in a "family planner" (calendar) and according to the possibility to do this or that task (if the kid is grown-up enough to make purchasing or to cook dinner?), task duration and its repetition and free time slots, put the tasks in a free timeslots randomly, so that all homework is subdivided through the family members (co-living-community) and at the and done.

### Which tracks do you think could be involved?
WD, UX

### How do you imagine User Experience Design could contribute to this project?
To do this task management app it is important to do it user friendly and easy to use for families and living communities. Finaly it would be cool to be able to use it in a mobile phone.

### How do you imagine Web Development could contribute to this project?
With Java/React knowledges to adapt this planner for use as mobile app?

### What are the most important challenges & bottlenecks of your project?
Design, control flow and of course more challenges while developing...

### What are the most important success factors of your project?
Small group and wish to create something usefull for everybody and for everyday... At least trial tests.

### Share your resources here:
[ProjectIdea_1_TechLab_Planner_ElenaIruchenkoMatlas.pdf](https://github.com/TechLabs-Berlin/project_proposals/files/13788080/ProjectIdea_1_TechLab_Planner_ElenaIruchenkoMatlas.pdf)

### Do you have any other remarks?
All additional ideas are welcome.

**Comment by catarinalouza** [comment]
Hi @ElenaIurchenkoMatlas, thanks for submitting your idea! 

> **Which tracks do you think could be involved?**
> WD, UX
> 

Since you're doing DS, can we assume you are not interested in working in this idea and are sharing it for the benefit of the community right? If that's a yes, then I would just like to clarify that if other techies are interested in this idea they may still form a project group to work on it.

**Comment by catarinalouza** [comment]
**For UX**: 
- This idea has great potential, loads of "room" for research and some nice features to work on. 
- Priority would be to decide on the main calendar features to show to users based on research. 
- This is also an idea that relies heavily on a graphic/visual approach so UX techies should feel comfortable with the UI part of it to build the prototype.

**For WD**:
- The idea is within the scope of work for WD techies, but with the limited time it might be beneficial to start small and integrate more features if time allows it.
- You will need a simple website or web-app with some placeholder timeslots/input fields for users engage with and add information.
- This would need to build with Javascript/React as WD techies don't learn Python.

Although it's not mentioned in your proposal, DS could potentially have a role to play. I'm waiting for confirmation from journey the team on how exactly could that work and if it falls within the DS scope of work. Otherwise, a UX + WD team is enough for a great result.

**Comment by ElenaIurchenkoMatlas** [comment]
Dear Catarina,

 it is open for every track and whole team to join this project idea. It was just a guess about UX and WD while I have no experience in such kind of projects.
Thank you and happy new year 🌲

Elena

> Hi @ElenaIurchenkoMatlas, thanks for submitting your idea!
> 
> > **Which tracks do you think could be involved?**
> > WD, UX
> 
> Since you're doing DS, can we assume you are not interested in working in this idea and are sharing it for the benefit of the community right? If that's a yes, then I would just like to clarify that if other techies are interested in this idea they may still form a project group to work on it.

Dear Catarina,

 it is open for every track and whole team to join this project idea. It was just a guess about UX and WD while I have no experience in such kind of projects.
Thank you and happy new year 🌲

Elena

**Comment by catarinalouza** [comment]
Approving this idea for scoping stage.

**Team requirements to be approved as project team would be:**
- [ ] 1 UX Techie 
- [ ] 1 UX Techie
- [ ] 1 WD Frontend Techie
- [ ] 1 WD Backend Techie

Since the original pitcher is doing a non required track, if you're interested, feel free to take ownership and assign yourself to this team and look for team members.

**Comment by PippiLo** [comment]
Hi, this project proposal sounds fantastic and similar to the idea that I was playing around with. I’d love to be involved as a ux techie.

**Comment by catarinalouza** [comment]
That's great @PippiLo, will assign you to this issue and you can start looking for team members!

**Comment by catarinalouza** [comment]
Hey @PippiLo, moving this project to '_accepted_' stage. If you find team members to join you, feel free to assign them to this issue.

**Comment by catarinalouza** [comment]
@PippiLo has shown interest to switch to a different project team, so this idea is looking for all team members again!
