### ISSUE TITLE
WiseInvest by Debanjan Choudhuri

### ISSUE THREAD

**Issue by fabianjkrueger** [TechLabs-Berlin/project_proposals#6]
### What is your project's name?
WiseInvest
### What's the problem you are trying to solve?
- We live in an age where a lot of the decisions we make are driven by FOMO. In some cases, these decisions don't really have a very big impact on our lives. Be it buying a new accessory or maybe going too crazy on a weekend we shouldn't have :D
However, on the flip-side there are decisions that when not well thought through can have wider consequences, like investments into stocks or crypto-currencies we know absolutely nothing about. A lack of education chasing potential gains can massively backfire leading to financial losses that can take years to recuperate.
- To add to the above, our generation and the ones to follow have a pretty bleak outlook when it comes to ensuring we can enjoy a decent post-retirement life. Let's face it, the German Pension Scheme just isn't good enough on it's own and we constantly hear about the different pillars that need to be in place like company pension schemes (if your workplace has one) or investing into the share market. Now when it comes to investments, how many of us have the necessary knowledge to confidently go about things?
- Also, not all of us can afford financial advisors that take care of these matters.
So to summarize, I'm trying to bridge the gap between a lack of knowledge and taking the plunge to add to one's retirement fund / buy that family home / or save for the next big holiday.
### What's your idea for a solution to the given "problem"?
A platform that provides users with:
1) Education Center: Keeping in mind that the goal would be to have an MVP in place, the focus would be on curated, readily-available videos around accounting and finance that one needs for building a value investing strategy.
2) Command Center: This is where a user has an overview of their portfolio,  company watch-list and valuation templates. This would be basically where all the existing excel templates that I have are available in one place and preferably, not in excel sheets :D
### Which tracks do you think could be involved?
DL/DS, WD, UX
### How do you imagine Deep Learning and/or Data Science could contribute to this project?
1. To help pull financial data from sources like Yahoo Finance / MarketScreener.
2. Summarizing key blocks of texts from annual statements (need to check the scope of this)
3. Link to key news updates on stock-listed companies.
### How do you imagine User Experience Design could contribute to this project?
It's a boring topic so UX Design has a key role to play in ensuring our platform is engaging and fun.
How should the education material be best presented so as to ensure users stay engaged?
How can we best ensure that the Command Center isn't a clustered mess of a lot of information?
### How do you imagine Web Development could contribute to this project?
WD is the backbone of this platform.
I already have a few excel templates that I envision could be used for this project.
WD plays a key role in translating these excel templates into the web-based platform that would then be available to all users.
### What are the most important challenges & bottlenecks of your project?
1. Availability of financial data feels like a major bottleneck. I'm really not sure how easy it would be to pull data from sources like Yahoo finance or Marketscreener.
2. Translating excel spreadsheets into web-based tables.
3. A personal bottleneck is to establish what an MVP would look like considering the 10 week timeframe :)
### What are the most important success factors of your project?
UX: Since the core topic is related to something "boring" like finance, providing a fun and engaging user experience is going to be key.
Data Accuracy: Again considering the topic, accurate data is of utmost importance!
### Share your resources here:
WIP: Miro Board with overview to link of templates, educational videos: https://miro.com/app/board/uXjVO7GYOfA=/?share_link_id=104020960118
### Do you have any other remarks? 
Looking forward to hearing suggestions :)

**Comment by fabianjkrueger** [comment]
Hey Debanjan, thank you for submitting this very nice project proposal! I think it is a great idea and it's obvious that you put a lot of thought into it.

Now, let's tackle some things we need to get resolved before it can enter the project phase.

**Comment by fabianjkrueger** [comment]
### Education Center
Great idea to provide resources for self-study. You specifically mentioned videos though. Are you planning to reference available videos from, e.g., YouTube? If you want to generate content yourself, you could also generate some text.

### Role of DL Techies
The DL techies are required to train neural networks for passing. I'd say pulling articles automatically is more like a backend WD job. The summarization of texts and information you mentioned would be a great idea for them to implement. Do you know it you could easily and legally access and process these texts? Do you have any data sets in case you cannot access them?

### Role of DS Techies
Similar things apply here. The DS techies have specific requirements for passing the program. They need to do some exploratory data analysis including visualizations. Finally, they need to fit a basic machine learning model to, e.g., tabular data. Do you have any sort of data for them to make use of? I personally think a great idea would be for them to contribute to the Education Center. Perhaps you can find some data (e.g., in Kaggle, HuggingFace, etc...) about portfolio development. They could then explore, visualize the data and fit a model to make some predictions for the future.

### Data Sets
As mentioned above: Both data related tracks need some sort of data. It is not necessarily your job to provide them with an exact specific one, but it is very important to check if there is anything topic related available that at least could be used by them in any scenario. If they do not have any kind of data, they are going to have a very bad time.

**Comment by fabianjkrueger** [comment]
### Role of UX Techies
Those are some great ideas for research tasks. I really love that you came up with this many ideas already! Probably, your UX team mates will find even more. UX techies will also provide a prototype of the app's design in Figma. You should share your ideas and Excel templates with them. They will likely make use of them and having some sort of blueprint for their prototype gives them a nice headstart. But expect them to incorporate their own individual ideas and visions, so prepare for it not looking 100% like you expected. They are learners as well, and as a team project, we welcome everyone to make their contribution.

### Role of WD Techies
The earlier you and the UX team can provide a prototype in Figma, the better. They can then use this to implement what you have planned. But again, also expect them not only to incorporate their own ideas, but also to reach some limits of their WD skills. In the best case, try to get at least one front end as well as a back end techie. Without both perspectives, you may not end up with a functioning prototype.

**Comment by fabianjkrueger** [comment]
### Miro Board
You mentioned it would contain some additional resources. There are no videos, and I have no access to view the linked Google sheets.

### Similar Project
There has been a similar project proposal: Investment guide by Elena Lurchenko-Matlas. I think it would be a great idea if you contacted them and had an exchange of ideas. Maybe you should join forces and work on a combined project. I'll leave this up to you.

**Comment by fabianjkrueger** [comment]
If you have any further questions or remarks, please just reach out to me! Thanks again for this beautiful project proposal!

**Comment by DecaDeD13** [comment]
> ### Education Center
> 
> Great idea to provide resources for self-study. You specifically mentioned videos though. Are you planning to reference available videos from, e.g., YouTube? If you want to generate content yourself, you could also generate some text.
> ### Role of DL Techies
> 
> The DL techies are required to train neural networks for passing. I'd say pulling articles automatically is more like a backend WD job. The summarization of texts and information you mentioned would be a great idea for them to implement. Do you know it you could easily and legally access and process these texts? Do you have any data sets in case you cannot access them?
> ### Role of DS Techies
> 
> Similar things apply here. The DS techies have specific requirements for passing the program. They need to do some exploratory data analysis including visualizations. Finally, they need to fit a basic machine learning model to, e.g., tabular data. Do you have any sort of data for them to make use of? I personally think a great idea would be for them to contribute to the Education Center. Perhaps you can find some data (e.g., in Kaggle, HuggingFace, etc...) about portfolio development. They could then explore, visualize the data and fit a model to make some predictions for the future.
> ### Data Sets
> 
> As mentioned above: Both data related tracks need some sort of data. It is not necessarily your job to provide them with an exact specific one, but it is very important to check if there is anything topic related available that at least could be used by them in any scenario. If they do not have any kind of data, they are going to have a very bad time.

The plan is to reference educational videos from Youtube :) 

**ROLE OF DS TECHIES:**
In terms of data sets, there's quite a bit available here from various different sources. I see that there's a yahoo finance library which has financial statements of publicly traded companies. So this would allow me to focus on the fun part which is prediction models :slightly_smiling_face: 

**ROLE OF DL TECHIES:**
When it comes to the question of legally accessing this information (SEC fillings), I think that's fine: https://sagemaker-jumpstart-industry-pack.readthedocs.io/en/latest/notebooks/finance/notebook4/SEC_10K_10Q_8K_section_extraction.html
What I'm really not sure is whether this is something achievable within the 10 week project phase period.

**Comment by DecaDeD13** [comment]
> ### Role of UX Techies
> 
> Those are some great ideas for research tasks. I really love that you came up with this many ideas already! Probably, your UX team mates will find even more. UX techies will also provide a prototype of the app's design in Figma. You should share your ideas and Excel templates with them. They will likely make use of them and having some sort of blueprint for their prototype gives them a nice headstart. But expect them to incorporate their own individual ideas and visions, so prepare for it not looking 100% like you expected. They are learners as well, and as a team project, we welcome everyone to make their contribution.
> ### Role of WD Techies
> 
> The earlier you and the UX team can provide a prototype in Figma, the better. They can then use this to implement what you have planned. But again, also expect them not only to incorporate their own ideas, but also to reach some limits of their WD skills. In the best case, try to get at least one front end as well as a back end techie. Without both perspectives, you may not end up with a functioning prototype.

Oh yes definitely, both groups are free to incorporate there respective ideas :)

**Comment by DecaDeD13** [comment]
> ### Miro Board
> 
> You mentioned it would contain some additional resources. There are no videos, and I have no access to view the linked Google sheets.
> ### Similar Project
> 
> There has been a similar project proposal: Investment guide by Elena Lurchenko-Matlas. I think it would be a great idea if you contacted them and had an exchange of ideas. Maybe you should join forces and work on a combined project. I'll leave this up to you.

My bad, the miro board now has been updated to include the video courses (link to youtube playlists) + excel templates (both sheets have been made public and should be viewable now). 

Will definitely be reaching out to Elena to have a discussion regarding this.

**Comment by fabianjkrueger** [comment]
> The plan is to reference educational videos from Youtube :)

Great! I was afraid you planned to create them within the 10 weeks :D

> **ROLE OF DS TECHIES:** In terms of data sets, there's quite a bit available here from various different sources. I see that there's a yahoo finance library which has financial statements of publicly traded companies. So this would allow me to focus on the fun part which is prediction models 🙂

Okay wow! yfinance is an awesome resource! It even returns data directly in pandas dataframes/series. This is perfect for DS techies! Glad you found that!

> **ROLE OF DL TECHIES:** When it comes to the question of legally accessing this information (SEC fillings), I think that's fine: https://sagemaker-jumpstart-industry-pack.readthedocs.io/en/latest/notebooks/finance/notebook4/SEC_10K_10Q_8K_section_extraction.html What I'm really not sure is whether this is something achievable within the 10 week project phase period.

Well, of that you can never be sure. You seem structured and motivated enough to make it happen! You should give it a try. Also, there is always the option to pivot the scope of your project. If it does not work out the end, go for a smaller goal or contact us and we will surely find some solution together.

**Comment by fabianjkrueger** [comment]
> My bad, the miro board now has been updated to include the video courses (link to youtube playlists) + excel templates (both sheets have been made public and should be viewable now).

Perfect, thank you very much!

> Will definitely be reaching out to Elena to have a discussion regarding this.

All the best with that! Seems very promising to me and I'd love to see you succeed together! If you still figure out that both projects are too different, then don't force it :)

**Comment by pynat** [comment]
Hi Debanjan, I am Natalie from the DataScience track. I am very much interested in the fintech field, crypto and investing. I am doing a lot of research on it and want to work in that area. So i would love to be part of that project!

**Comment by DecaDeD13** [comment]
> Hi Debanjan, I am Natalie from the DataScience track. I am very much interested in the fintech field, crypto and investing. I am doing a lot of research on it and want to work in that area. So i would love to be part of that project!

Hi Natalie, thanks for reaching out! Would be happy to work with you on this! There's a possibility this project is merged with another one on a similar topic. Either way, things should be clear in a day or two :)

**Comment by fabianjkrueger** [comment]
### Track Composition
@DecaDeD13 All the best for you during the team formation phase! 
Regarding the team's composition, the minimum acceptance criteria for team formation are:

* [ ] 2 Data Science
* [ ] 2 Web Development (1 back end & 1 front end)
* [ ] 2 User Experience Design
* [ ] 1 Deep Learning

You can accept more than that, of course. For example, I recommend including two DL techies. The maximum team size is about 10 techies. In case we need to get specific about that, we'll have a brief discussion. 

Also, you can now pitch and open this project up for discussion in the bl-project_ideas channel. If you like, I can also make the announcement. Just pn me in Slack. But I feel like you can give it a nice personal touch and add some more info or perspective than what can be found here in GitHub if you do it yourself.

Once you found interested techies and team members, assign them to this issue if they agree :)

**Comment by mjkamegawa** [comment]
Hi! I was about to submit a similar to this project, the difference is that my idea is a decentralized exchange for junior traders and people interested in investing, but with no knowledge, to earn more than the regular types of existing investment with lower risk even than pro, because it's going to be connected to the new sources.
I'm in the UX track btw

**Comment by sfngrz** [comment]
Hey @DecaDeD13,

Stefano here from the WD track, really like the project theme! Are you still looking for a front end dev?

**Comment by pynat** [comment]
Hi Stefano, as far as I know this project still is looking for a front end dev : ) maybe text Debanjan on slack, he also didn't get a notification that i commented here.

**Comment by DecaDeD13** [comment]
> Hey @DecaDeD13,
> 
> Stefano here from the WD track, really like the project theme! Are you still looking for a front end dev?

Hi Stefano! Yes, we're still looking for WD techies :) Can I go ahead and assign you to this project as the FE dev?

**Comment by sfngrz** [comment]
Hey  @DecaDeD13,
thanks for the reply! in the meantime I ve already accepted to be in another project, but I also notified techlabs than in case they need a different approach I really like this project too!

**Comment by dari11111** [comment]
Hey there! @DecaDeD13, Do you still have place in your team for WD part? I would like to join the project and be curious and enthusiastic on the project phase:)

**Comment by DecaDeD13** [comment]
Hi! Yes we're still looking for WD techies. Would be happy to include
you in the project :)
