### ISSUE TITLE
Gallery Organizer by Paula Hierzi

### ISSUE THREAD

**Issue by valiantone** [TechLabs-Berlin/project_proposals#7]
### What is your project's name?
Gallery organizer

### What's the problem you are trying to solve?

Organizing my pictures, screenshots especially, safely. Sorting it into Albums

### What's your idea for a solution to the given "problem"?
I always especially in this course make screenshots of things I learnn I wanna read, of inspiration, things I want to shop so I have this big album of screenshots. But same with pictures I am making. Or WhatsApp pictures that come from a certain group ( and i dont want to have them). ETC. ...

### Which tracks do you think could be involved?
DL/DS, WD, UX

### How do you imagine Deep Learning and/or Data Science could contribute to this project?
DL recognizing certain aspects and giving that information to DS to sort it into Albums. Making an App(WD) that is accessible, clear and simple(UX).
How to make it very safe ? Not sure which job that is since we are working with personal data.

### How do you imagine User Experience Design could contribute to this project?
Making it clear, accessible, simple, stylish, ...

### How do you imagine Web Development could contribute to this project?
The App needs to be created by you!!!

### What are the most important challenges & bottlenecks of your project?
Safety ?
DL Team can you find a way to find important information to sort ?
How can Data Science and Web Development work together to make different albums out of it ?

### What are the most important success factors of your project?
Simplicity. Maybe each time you make a picture it asks you for info to sort it into an album?
Their will be not sorted and sorted albums.

### Share your resources here:
https://play.google.com/store/apps/details?id=co.slidebox

### Do you have any other remarks?
I am working on my other project (if that works). Just wanted to put it out there!

**Comment by valiantone** [comment]
Idea is very clear, great job on that @Rustingheart. We will have to get a little creative with some features to include all tracks. WD + UX should work together on interface; WD + DS on storage backend. **Now main concern:** and this may kill the idea; for track requirements (to apply curriculum), we are limited to a webapp and not a native app. Within that ecosystem now, it makes sense to repurpose this application to perhaps offer more features. Can WD work to add notifications and alerts based on screenshot content? This can be fleshed out later but please list out a few example features you can imagine that will require WD efforts. 

**Now for DS:** I can imagine a more concrete use case; you will need some tags to sort and filter your screenshots. Now DS can work on giving (auto)suggestions for these images. To do that will perhaps some text extraction from images (maybe taking help of some DL techies). Once you have that simple document classification (NLP) can help you suggest labels based on content. Just an example. But again to move this forward you will need to provide at least one concrete use-case even if it is later changed after team formation.

**The UX team's task here is more independent and hence you can move this forward to recruiting UX techies who would like to be associated with the project.**

#### To Do's

- [ ] List out a few features (one or two) for the WD team to work on as part of a webapp (mobile-first)
- [ ] Define maybe one clear function for the DS techies to build for this project
- [ ] Go recruit some UX techies and add them here!

**Comment by Rustingheart** [comment]
Wow thank you so much for the advise!
 I think for this idea a native App would make much more sense. As it is not possible I think it's good to know that it will be more a learning playground to upload pictures and sort them . 
But not a Real live project.

**Comment by Rustingheart** [comment]
I would like to give this Idea on to someone that is interested as I would like to concentrate on my other proposal.

**Comment by valiantone** [comment]
Understood, since @Rustingheart would like to work on their other proposals; moving this back to `proposal` stage since it needs a new owner. 

**Please respond and let us know if any techie would like to take this over!**
