### ISSUE TITLE
Investment guide by Elena Iurchenko-Matlas

### ISSUE THREAD

**Issue by fabianjkrueger** [TechLabs-Berlin/project_proposals#8]
### What is your project's name?
Investment guide
### What's the problem you are trying to solve?
There are many many sources in internet with overwhelming offers about investment and most of them are based on advertising of a product of the own institution and not  wide audience oriented, so that I personally had to visit investment courses to understand  the process and all stept i had to go throught. On investment couse I met different people from young to old who was lost and confused about investing his/her money.
### What's your idea for a solution to the given "problem"?
Offering an accessible and easy to understand investment guide for beginner that describes all the steps from A to Z.
### Which tracks do you think could be involved?
WD, UX, DL/DS
### How do you imagine Deep Learning and/or Data Science could contribute to this project?
Impact to algorithms bilding and data evaluation for the end result
### How do you imagine User Experience Design could contribute to this project?
It schould be a user friendly application/guide like some already existing apps that simplify the process of filling tax declaration Elster.
### How do you imagine Web Development could contribute to this project?
Because of great spectrum of information it could be put in a webseite form for clear view.
### What are the most important challenges & bottlenecks of your project?
Collect a data about banks and investment institution, combining and visualising it in userfriendly way.
### What are the most important success factors of your project?
It looks like as a big project that needs some research and expert knowledges, so if you are financial expert and can impact to this idea, your are very welcome...
### Would you like to add an optional Pitch deck to support your idea in 6 to 8 slides?
https://docs.google.com/presentation/d/1BPEFonMtRHyvixG2QpoN75pC0sQX-EAA/edit?usp=sharing&ouid=116779314156128684048&rtpof=true&sd=true

**Comment by fabianjkrueger** [comment]
Hi Elena! Thank you very much for this nice project proposal! It's already well-planned and laid out in your pitch deck. Bonus points for that!

In order to get this to the next stage, we will have to address just a few things.

**Comment by fabianjkrueger** [comment]
During the project phase, as you know, each track has very specific requirements for passing. I think you idea and proposal provides a great starting point for a TechLabs project phase. However, we need to make sure that techies of all involved tracks get the chance to fulfill these requirements.

### Web Development
This is probably the most obvious one here. Their job is to build a website or mobile app. Did you already decide that you prefer the web format? When assembling your team, try to find a person from front end as well as from back end in order to not only make the website beautiful, but to also make it work by connecting all the parts behind the scenes. Finding techies from the back end specialisation has been one of the critical factors for success in a lot of projects from previous semesters.

### User Experience Design
Also their role is well covered in your project proposal. They can help make the website more engaging and fun to use. Did you also already think about some specific ideas for user research they can do? Is there anything you would like them to find out? Any areas that are uncertain or need optimization?

**Comment by fabianjkrueger** [comment]
### Data Science and Deep Learning
This is one of the issues we need to address before going moving the proposal to the next stage. You mentioned you could imagine including techies from both our data centric tracks. For them, it is absolutely crucial to have some data ready at hand they can evaluate. If there is nothing for them to analyze, they will not be able to contribute and pass. Being a DS techie yourself, maybe did you already have a look at some usable data sets? Is there anything out there for these tracks? Examples for data science techies are tabular data of portfolio developments or streams of money invested in certain markets. I am sure you can find something out there! In the case of deep learning, you can get a little more sophisticated. They can work mainly with text or image data. Perhaps they can summarize some information from the web. Please provide some ideas and potential sources of data for them to use!

**Comment by fabianjkrueger** [comment]
### Similar Project

There has been a similar project proposal: WiseInvest by Debanjan Choudhuri. I think it would be a great idea if you contacted them and had an exchange of ideas. I feel like both project proposals would complement and profit from each other.

**Comment by DecaDeD13** [comment]
Hi @ElenaIurchenkoMatlas , Janosh suggested reaching out to you as we might have similar project proposals. Would be happy to have a discussion to see if there are potential synergies :)

**Comment by ElenaIurchenkoMatlas** [comment]
> Hi @ElenaIurchenkoMatlas , Janosh suggested reaching out to you as we might have similar project proposals. Would be happy to have a discussion to see if there are potential synergies :)

Hi Debanjan, I have already checked you project and its look like similar, but also different. Yours is more complicated I guess, you want to accumulate learning material base and portfolio page together. I would concentrate better on one taks for such small period of time for the project, like just education concept. 
Any way it would be nice to have an exchange of ideas with you.

**Comment by ElenaIurchenkoMatlas** [comment]
> ### Data Science and Deep Learning
> This is one of the issues we need to address before going moving the proposal to the next stage. You mentioned you could imagine including techies from both our data centric tracks. For them, it is absolutely crucial to have some data ready at hand they can evaluate. If there is nothing for them to analyze, they will not be able to contribute and pass. Being a DS techie yourself, maybe did you already have a look at some usable data sets? Is there anything out there for these tracks? Examples for data science techies are tabular data of portfolio developments or streams of money invested in certain markets. I am sure you can find something out there! In the case of deep learning, you can get a little more sophisticated. They can work mainly with text or image data. Perhaps they can summarize some information from the web. Please provide some ideas and potential sources of data for them to use!

Hi Fabian,
unfortunately I searched all the week for a data for my projekt, but I could'n find the right one. I have just a list of all financial institutions in Germany, but without services they provide, and to go through each institution manualy will take to much time to collect some info. 
Basically I have just 50% of theoretical information to bild an inquirer and collect info from user of what are the expactations and goals about investment  and with this data I can make a deciccion, what kind of investment the user need. But I cant compare and offer a real financial institution in the end, what should be the main purpose of my project...

**Comment by ElenaIurchenkoMatlas** [comment]
> ### Data Science and Deep Learning
> This is one of the issues we need to address before going moving the proposal to the next stage. You mentioned you could imagine including techies from both our data centric tracks. For them, it is absolutely crucial to have some data ready at hand they can evaluate. If there is nothing for them to analyze, they will not be able to contribute and pass. Being a DS techie yourself, maybe did you already have a look at some usable data sets? Is there anything out there for these tracks? Examples for data science techies are tabular data of portfolio developments or streams of money invested in certain markets. I am sure you can find something out there! In the case of deep learning, you can get a little more sophisticated. They can work mainly with text or image data. Perhaps they can summarize some information from the web. Please provide some ideas and potential sources of data for them to use!

What do you think if I use this statisatical info [https://www.mobilebanking.de/magazin/banken-ranking-die-groessten-banken-deutschlands.html](url) and on its basic research the info about financial institutions that are the most popular and reliable to its customers,,,al least I dont need all the bank and brokers ,but the best.

**Comment by valiantone** [comment]
Hey @ElenaIurchenkoMatlas, here is a comment from UX techie @mistersouza who would like to be associated with this project:
> This project is incredibly promissing, and I'm very enthusiastic about participating in it. I am currently at the ux track, looking forwarding to helping you building up your idea.

**Comment by ElenaIurchenkoMatlas** [comment]
> During the project phase, as you know, each track has very specific requirements for passing. I think you idea and proposal provides a great starting point for a TechLabs project phase. However, we need to make sure that techies of all involved tracks get the chance to fulfill these requirements.
> 
> ### Web Development
> This is probably the most obvious one here. Their job is to build a website or mobile app. Did you already decide that you prefer the web format? When assembling your team, try to find a person from front end as well as from back end in order to not only make the website beautiful, but to also make it work by connecting all the parts behind the scenes. Finding techies from the back end specialisation has been one of the critical factors for success in a lot of projects from previous semesters.
> 
> ### User Experience Design
> Also their role is well covered in your project proposal. They can help make the website more engaging and fun to use. Did you also already think about some specific ideas for user research they can do? Is there anything you would like them to find out? Any areas that are uncertain or need optimization?

1) I think that a Website would be a better version for this project, because it will provide better overview of all posible investment organisations after considering which type of investment is the best for the particular user. 
2) At the first stage of the end prototype the goal is create an algorithm that collect the data from the user, like small inquirer where we can use some images or animation to every question.. At the end of data collecting the algorithm should give to user a desission or a list of posibilities what is the best investment product for him/her...These could be presented in a form of ledder from the best one to the last one or have different colours , like green for the best and red for the worthest one.
3) In the last step the user will become the real financial institution to overview, that mets inverstment requirement, here we can also present it in order from the best one according to the offered conditions to the last one. The best one can be emphasised and have drop down menu with all services they provide and the last one be like an option. 
3)

**Comment by ElenaIurchenkoMatlas** [comment]
> Hey @ElenaIurchenkoMatlas, here is a comment from UX techie @mistersouza who would like to be associated with this project:
> 
> > This project is incredibly promissing, and I'm very enthusiastic about participating in it. I am currently at the ux track, looking forwarding to helping you building up your idea.

Hey @mistersouza, welcome to the project =) thank U for showing your interest.

**Comment by ElenaIurchenkoMatlas** [comment]
> During the project phase, as you know, each track has very specific requirements for passing. I think you idea and proposal provides a great starting point for a TechLabs project phase. However, we need to make sure that techies of all involved tracks get the chance to fulfill these requirements.
> 
> ### Web Development
> This is probably the most obvious one here. Their job is to build a website or mobile app. Did you already decide that you prefer the web format? When assembling your team, try to find a person from front end as well as from back end in order to not only make the website beautiful, but to also make it work by connecting all the parts behind the scenes. Finding techies from the back end specialisation has been one of the critical factors for success in a lot of projects from previous semesters.
> 
> ### User Experience Design
> Also their role is well covered in your project proposal. They can help make the website more engaging and fun to use. Did you also already think about some specific ideas for user research they can do? Is there anything you would like them to find out? Any areas that are uncertain or need optimization?

what if we use emotions and put a human pictire or animation to every desission 
![image](https://github.com/TechLabs-Berlin/project_proposals/assets/144584067/e4bc309a-283a-44ad-9cce-35893fa91ae9)

**Comment by fabianjkrueger** [comment]
Hi @ElenaIurchenkoMatlas!
Thank you for addressing the issues!

## Project Proposal in General
The general project idea and proposal are formulated very well. I am convinced that you will be able to realize the project, and also do so within the scope of our TechLabs project phase. We still have two more days to complete this and getting the project accepted. There is a final problem we need to tackle.

## WebDev and UX Design
The roles of these two tracks are laid out very clearly, and there will be a sufficient number of tasks for them to realise. They can be included in your project. They will build and optimize the website together.

## Data Science and Deep Learning
Among the requirements for competing the DS and DL tracks at TechLabs are handling data and training a machine learning algorithm. Without this, respective techies will not pass the program and not receive the certificate. I do not say that each and every project actually even needs machine learning or would benefit from it, but since this is an educational program, the techies need to implement this to pass. Otherwise, the point of the program would be missed.

So, if these tracks do not have data to work with, they cannot really contribute to the project. They will have so simulate data or make up features that are not actually needed, which often leads to frustration. I'd say the website provided about the largest German financial institutes is not actually suitable. The data can be visualized, but there is not much use in doing an exploratory data analysis here, and it cannot be used to train an ML algorithm, since it is too small. Also, there isn't any data set for DL at all.

Regarding the implementation of the recommendation algorithm, you plan to base this on acquired knowledge using user input and to implement rules for the decision making instead of training an algorithm on data. Because of that, this task is well suited for WD techies, but not so much for DS techies, unfortunately.

We have a couple of options now:
1. You can have one more look for datasets at [Kaggle](https://www.kaggle.com/datasets), [HuggingFace](https://huggingface.co/datasets) and [OpenML](https://openml.org/), preferably until tomorrow. If you find anything usable (please be sincere), you can include DS or rather DL.
2. If you do not find any usable, you cannot include these tracks. I think, however, that you can also realize a very successful project without them. Building a user friendly website for recommendation based on user input will be possible with just WD and UX. So, you can also just assemble a team of exclusively WD and UX techies.
3. You can talk to this similar project once more and decide if you can find a solution for this together.

Wishing you all the best!

**Comment by valiantone** [comment]
Absolutely agree with @fabianjkrueger!

So @ElenaIurchenkoMatlas to move this towards acceptance:

 1. You can let us know if you would still like to move this project forward as only WD + UX, this would then be a simple rule-based application making some recommendations using some programmed logic. **No DS**
 
2. If you can still think of an application for DS techies, please suggest some tasks even if you do not have a dataset in mind. We can assist in suggesting datasets if you can provide a more clear picture of what you are imaging the DS techies will build. But without this as Janosch mentioned it is hard to even justify DS techies to this project.

Let us know and we can make a decision at earliest if this project moves ahead or maybe even it's better to kill this proposal if your other idea is already moving ahead!

**Comment by ElenaIurchenkoMatlas** [comment]
> Absolutely agree with @fabianjkrueger!
> 
> So @ElenaIurchenkoMatlas to move this towards acceptance:
> 
> 1. You can let us know if you would still like to move this project forward as only WD + UX, this would then be a simple rule-based application making some recommendations using some programmed logic. **No DS**
> 2. If you can still think of an application for DS techies, please suggest some tasks even if you do not have a dataset in mind. We can assist in suggesting datasets if you can provide a more clear picture of what you are imaging the DS techies will build. But without this as Janosch mentioned it is hard to even justify DS techies to this project.
> 
> Let us know and we can make a decision at earliest if this project moves ahead or maybe even it's better to kill this proposal if your other idea is already moving ahead!

Hello Zubin, thank you for your comment, 
I'm realistic about the info/data for the project I already have and I dont, so because of leak of dataset for DS to be able to contribute to this project idea, I decided to give up this idea for someone from WD/UX Track.

**Comment by ElenaIurchenkoMatlas** [comment]
> Hi @ElenaIurchenkoMatlas! Thank you for addressing the issues!
> 
> ## Project Proposal in General
> The general project idea and proposal are formulated very well. I am convinced that you will be able to realize the project, and also do so within the scope of our TechLabs project phase. We still have two more days to complete this and getting the project accepted. There is a final problem we need to tackle.
> 
> ## WebDev and UX Design
> The roles of these two tracks are laid out very clearly, and there will be a sufficient number of tasks for them to realise. They can be included in your project. They will build and optimize the website together.
> 
> ## Data Science and Deep Learning
> Among the requirements for competing the DS and DL tracks at TechLabs are handling data and training a machine learning algorithm. Without this, respective techies will not pass the program and not receive the certificate. I do not say that each and every project actually even needs machine learning or would benefit from it, but since this is an educational program, the techies need to implement this to pass. Otherwise, the point of the program would be missed.
> 
> So, if these tracks do not have data to work with, they cannot really contribute to the project. They will have so simulate data or make up features that are not actually needed, which often leads to frustration. I'd say the website provided about the largest German financial institutes is not actually suitable. The data can be visualized, but there is not much use in doing an exploratory data analysis here, and it cannot be used to train an ML algorithm, since it is too small. Also, there isn't any data set for DL at all.
> 
> Regarding the implementation of the recommendation algorithm, you plan to base this on acquired knowledge using user input and to implement rules for the decision making instead of training an algorithm on data. Because of that, this task is well suited for WD techies, but not so much for DS techies, unfortunately.
> 
> We have a couple of options now:
> 
> 1. You can have one more look for datasets at [Kaggle](https://www.kaggle.com/datasets), [HuggingFace](https://huggingface.co/datasets) and [OpenML](https://openml.org/), preferably until tomorrow. If you find anything usable (please be sincere), you can include DS or rather DL.
> 2. If you do not find any usable, you cannot include these tracks. I think, however, that you can also realize a very successful project without them. Building a user friendly website for recommendation based on user input will be possible with just WD and UX. So, you can also just assemble a team of exclusively WD and UX techies.
> 3. You can talk to this similar project once more and decide if you can find a solution for this together.
> 
> Wishing you all the best!

Hello Fabian, 
I searched the whole last week, but the only data I have found is from European Central Bank and is in attachment. 
To fulfil these data with extra material I wanted for my project will take me to much time, thats why I decided to give up my project for other techies from WD/UX. 

[1. ECB_Investment fund per countrie and investment policy.pdf](https://github.com/TechLabs-Berlin/project_proposals/files/13975995/1.ECB_Investment.fund.per.countrie.and.investment.policy.pdf)
[2. ECB_Insurance Corporations per country and type of economic activit.pdf](https://github.com/TechLabs-Berlin/project_proposals/files/13975996/2.ECB_Insurance.Corporations.per.country.and.type.of.economic.activit.pdf)
[3. EuroAreaFinancialInstiotutions.csv](https://github.com/TechLabs-Berlin/project_proposals/files/13975997/3.EuroAreaFinancialInstiotutions.csv)
[3.Pension Funds per country and type of scheme.pdf](https://github.com/TechLabs-Berlin/project_proposals/files/13975998/3.Pension.Funds.per.country.and.type.of.scheme.pdf)
[4. top-industrie-deutschland_for shares decission making.xlsx](https://github.com/TechLabs-Berlin/project_proposals/files/13975999/4.top-industrie-deutschland_for.shares.decission.making.xlsx)
