### ISSUE TITLE
Investment guide by Elena Iurchenko-Matlas

### ISSUE THREAD

**Issue by mistersouza** [TechLabs-Berlin/project_proposals#9]
This project is incredibly promissing, and I'm very enthusiastic about participating in it.

**Comment by catarinalouza** [comment]
Hi @mistersouza, please comment about your interest in this project idea in the correct git issue! You can find it in this link: [https://github.com/TechLabs-Berlin/project_proposals/issues/8https://github.com/TechLabs-Berlin/project_proposals/issues/8](url)

Also make sure to mention your track when showing interest! We will close this copy of the git issue in 48h max so there's no duplicates. Thank you!

**Comment by catarinalouza** [comment]
Closing this issue as mentioned above.
